/*
   NEET Chapter Database
   Complete syllabus with ALL chapters for Physics, Chemistry, Biology
   Each chapter includes: marks, priority, topics, formulas, etc.
*/

const ChapterDatabase = {
    // Configuration
    totalMarksAvailable: 720,
    targetScore: 600,

    // ============================================
    // BIOLOGY - 20 Chapters
    // ============================================
    biology: [
        {
            id: 'bio-01',
            name: 'Digestion & Absorption',
            priority: 'high',
            marks: 15,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Digestive System', 'Enzymes', 'Absorption', 'Peristalsis'],
            weakPoints: []
        },
        {
            id: 'bio-02',
            name: 'Breathing & Respiration',
            priority: 'high',
            marks: 14,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Respiratory System', 'Gas Exchange', 'Aerobic Respiration', 'Anaerobic Respiration'],
            weakPoints: []
        },
        {
            id: 'bio-03',
            name: 'Body Fluids & Circulation',
            priority: 'high',
            marks: 16,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Blood', 'Lymph', 'Cardiac Output', 'Blood Circulation'],
            weakPoints: []
        },
        {
            id: 'bio-04',
            name: 'Excretory System',
            priority: 'high',
            marks: 13,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Kidney Structure', 'Urine Formation', 'Osmoregulation'],
            weakPoints: []
        },
        {
            id: 'bio-05',
            name: 'Locomotion & Movement',
            priority: 'medium',
            marks: 12,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Skeletal System', 'Muscle Contraction', 'Joint Types'],
            weakPoints: []
        },
        {
            id: 'bio-06',
            name: 'Neural Control',
            priority: 'high',
            marks: 15,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Neuron Structure', 'Synapse', 'Reflex Arc', 'Brain & Spinal Cord'],
            weakPoints: []
        },
        {
            id: 'bio-07',
            name: 'Chemical Coordination',
            priority: 'high',
            marks: 14,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Hormones', 'Endocrine Glands', 'Feedback Mechanism'],
            weakPoints: []
        },
        {
            id: 'bio-08',
            name: 'Human Reproduction',
            priority: 'high',
            marks: 14,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Reproductive Organs', 'Gametogenesis', 'Fertilization', 'Pregnancy'],
            weakPoints: []
        },
        {
            id: 'bio-09',
            name: 'Reproductive Health',
            priority: 'medium',
            marks: 8,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['STDs', 'Contraception', 'Infertility'],
            weakPoints: []
        },
        {
            id: 'bio-10',
            name: 'Mendelian Genetics',
            priority: 'high',
            marks: 16,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Laws of Inheritance', 'Monohybrid Cross', 'Dihybrid Cross'],
            weakPoints: []
        },
        {
            id: 'bio-11',
            name: 'Molecular Basis of Inheritance',
            priority: 'high',
            marks: 15,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['DNA Structure', 'Replication', 'Transcription', 'Translation'],
            weakPoints: []
        },
        {
            id: 'bio-12',
            name: 'Evolution',
            priority: 'medium',
            marks: 12,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Evidences of Evolution', 'Mechanism', 'Speciation'],
            weakPoints: []
        },
        {
            id: 'bio-13',
            name: 'Photosynthesis',
            priority: 'high',
            marks: 14,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Light Reactions', 'Dark Reactions', 'Calvin Cycle'],
            weakPoints: []
        },
        {
            id: 'bio-14',
            name: 'Respiration in Plants',
            priority: 'medium',
            marks: 12,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Aerobic Respiration', 'Anaerobic Respiration', 'Fermentation'],
            weakPoints: []
        },
        {
            id: 'bio-15',
            name: 'Plant Growth & Regulators',
            priority: 'medium',
            marks: 11,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Auxins', 'Gibberellins', 'Cytokinins', 'Tropism'],
            weakPoints: []
        },
        {
            id: 'bio-16',
            name: 'Ecosystem',
            priority: 'medium',
            marks: 12,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Components', 'Energy Flow', 'Nutrient Cycling'],
            weakPoints: []
        },
        {
            id: 'bio-17',
            name: 'Biodiversity & Conservation',
            priority: 'medium',
            marks: 10,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Biodiversity Levels', 'Hotspots', 'Conservation'],
            weakPoints: []
        },
        {
            id: 'bio-18',
            name: 'Environmental Issues',
            priority: 'low',
            marks: 8,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Pollution', 'Ozone Depletion', 'Global Warming'],
            weakPoints: []
        },
        {
            id: 'bio-19',
            name: 'Biotechnology & Applications',
            priority: 'medium',
            marks: 10,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Genetic Engineering', 'PCR', 'Cloning'],
            weakPoints: []
        },
        {
            id: 'bio-20',
            name: 'Cell Biology & Diversity',
            priority: 'high',
            marks: 14,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            topics: ['Cell Structure', 'Cell Division', 'Taxonomy'],
            weakPoints: []
        }
    ],

    // ============================================
    // CHEMISTRY - 25 Chapters
    // ============================================
    chemistry: [
        {
            id: 'chem-01',
            name: 'Mole Concept',
            priority: 'high',
            marks: 16,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['n=m/M', 'Molarity', 'Molality'],
            topics: ['Molar Mass', 'Stoichiometry', 'Limiting Reagent']
        },
        {
            id: 'chem-02',
            name: 'Thermodynamics',
            priority: 'high',
            marks: 15,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['ΔH', 'ΔG=ΔH-TΔS', 'ΔS'],
            topics: ['Enthalpy', 'Entropy', 'Free Energy', 'Hess Law']
        },
        {
            id: 'chem-03',
            name: 'Chemical Equilibrium',
            priority: 'high',
            marks: 15,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['Kc', 'Kp', 'Qc'],
            topics: ['Law of Equilibrium', 'Le Chatelier', 'Ionic Equilibrium']
        },
        {
            id: 'chem-04',
            name: 'Electrochemistry',
            priority: 'high',
            marks: 14,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['E°cell', 'Nernst Equation', 'Faraday Laws'],
            topics: ['Redox', 'Galvanic Cells', 'Electrolysis']
        },
        {
            id: 'chem-05',
            name: 'Chemical Kinetics',
            priority: 'high',
            marks: 13,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['Rate Law', 'k=Ae^(-Ea/RT)', 'Half-life'],
            topics: ['Rate of Reaction', 'Order', 'Activation Energy']
        },
        {
            id: 'chem-06',
            name: 'Solutions',
            priority: 'medium',
            marks: 12,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['Raoult\'s Law', 'Colligative Properties'],
            topics: ['Types', 'Concentration', 'Colligative Properties']
        },
        {
            id: 'chem-07',
            name: 'General Organic Chemistry',
            priority: 'high',
            marks: 16,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Nomenclature', 'Isomerism', 'Reaction Mechanism']
        },
        {
            id: 'chem-08',
            name: 'Hydrocarbons',
            priority: 'high',
            marks: 15,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Alkanes', 'Alkenes', 'Alkynes', 'Aromatic']
        },
        {
            id: 'chem-09',
            name: 'Haloalkanes & Haloarenes',
            priority: 'medium',
            marks: 11,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Properties', 'Reactions', 'Substitution Elimination']
        },
        {
            id: 'chem-10',
            name: 'Alcohols, Phenols & Ethers',
            priority: 'medium',
            marks: 12,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Preparation', 'Reactions', 'Acidity']
        },
        {
            id: 'chem-11',
            name: 'Aldehydes & Ketones',
            priority: 'high',
            marks: 13,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Nucleophilic Addition', 'Condensation', 'Oxidation']
        },
        {
            id: 'chem-12',
            name: 'Carboxylic Acids & Derivatives',
            priority: 'high',
            marks: 13,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Acidity', 'Esterification', 'Esters Amides']
        },
        {
            id: 'chem-13',
            name: 'Amines',
            priority: 'medium',
            marks: 11,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Classification', 'Basicity', 'Reactions']
        },
        {
            id: 'chem-14',
            name: 'Biomolecules',
            priority: 'high',
            marks: 12,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Carbohydrates', 'Proteins', 'Lipids', 'Nucleic Acids']
        },
        {
            id: 'chem-15',
            name: 'Polymers',
            priority: 'low',
            marks: 8,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Types', 'Polymerization', 'Properties']
        },
        {
            id: 'chem-16',
            name: 'Atomic Structure',
            priority: 'high',
            marks: 14,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['Bohr\'s Model', 'Quantum Numbers'],
            topics: ['Nucleus', 'Electrons', 'Orbitals', 'Quantum Mechanics']
        },
        {
            id: 'chem-17',
            name: 'Periodic Classification',
            priority: 'high',
            marks: 13,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Periodic Trends', 'Periodic Properties', 'Classification']
        },
        {
            id: 'chem-18',
            name: 'Chemical Bonding',
            priority: 'high',
            marks: 15,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['Electronegativity', 'Bond Energy'],
            topics: ['Ionic Covalent Metallic', 'Bonding', 'Lewis Structures']
        },
        {
            id: 'chem-19',
            name: 'Coordination Compounds',
            priority: 'high',
            marks: 12,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Ligands', 'Naming', 'Isomerism', 'Bonding']
        },
        {
            id: 'chem-20',
            name: 'd-block Elements',
            priority: 'high',
            marks: 13,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Electronic Configuration', 'Properties', 'Compounds']
        },
        {
            id: 'chem-21',
            name: 'f-block Elements',
            priority: 'medium',
            marks: 8,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Lanthanides', 'Actinides']
        },
        {
            id: 'chem-22',
            name: 'p-block Elements',
            priority: 'high',
            marks: 14,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Boron Group', 'Carbon Group', 'Nitrogen Group', 'Halogens', 'Noble Gases']
        },
        {
            id: 'chem-23',
            name: 's-block Elements',
            priority: 'medium',
            marks: 10,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Alkali Metals', 'Alkaline Earth Metals']
        },
        {
            id: 'chem-24',
            name: 'Environmental Chemistry',
            priority: 'low',
            marks: 7,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Pollution', 'Green Chemistry']
        },
        {
            id: 'chem-25',
            name: 'Practical Organic Chemistry',
            priority: 'medium',
            marks: 9,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: [],
            topics: ['Identification', 'Qualitative Analysis']
        }
    ],

    // ============================================
    // PHYSICS - 15 Chapters
    // ============================================
    physics: [
        {
            id: 'phys-01',
            name: 'Laws of Motion',
            priority: 'high',
            marks: 16,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['F=ma', 'p=mv', 'F₁₂=-F₂₁'],
            topics: ['Newton\'s Laws', 'Friction', 'Momentum']
        },
        {
            id: 'phys-02',
            name: 'Work, Energy & Power',
            priority: 'high',
            marks: 15,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['W=Fs', 'KE=½mv²', 'PE=mgh', 'P=W/t'],
            topics: ['Work', 'Energy Conservation', 'Power', 'Collision']
        },
        {
            id: 'phys-03',
            name: 'Rotational Motion',
            priority: 'high',
            marks: 14,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['τ=Iα', 'L=Iω', 'I=MR²'],
            topics: ['Angular Motion', 'Torque', 'Angular Momentum', 'Rolling']
        },
        {
            id: 'phys-04',
            name: 'Gravitation',
            priority: 'high',
            marks: 14,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['F=GMm/r²', 'g=GM/R²', 'v=√(GM/r)'],
            topics: ['Newton\'s Law', 'Orbital Mechanics', 'Satellite Motion']
        },
        {
            id: 'phys-05',
            name: 'Properties of Matter',
            priority: 'medium',
            marks: 12,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['Stress', 'Strain', 'Young\'s Modulus'],
            topics: ['Elasticity', 'Fluid Pressure', 'Surface Tension', 'Viscosity']
        },
        {
            id: 'phys-06',
            name: 'Electrostatics',
            priority: 'high',
            marks: 16,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['F=kq₁q₂/r²', 'E=kQ/r²', 'V=W/q'],
            topics: ['Coulomb\'s Law', 'Electric Field', 'Electric Potential', 'Capacitance']
        },
        {
            id: 'phys-07',
            name: 'Current Electricity',
            priority: 'high',
            marks: 15,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['I=Q/t', 'V=IR', 'P=VI', 'ε=E/q'],
            topics: ['Ohm\'s Law', 'Resistance', 'EMF', 'Circuits']
        },
        {
            id: 'phys-08',
            name: 'Magnetism',
            priority: 'high',
            marks: 14,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['F=BIL', 'B=μ₀I/2πr', 'τ=NIAB'],
            topics: ['Magnetic Field', 'Forces', 'Torque', 'Earth\'s Magnetism']
        },
        {
            id: 'phys-09',
            name: 'Electromagnetic Induction',
            priority: 'high',
            marks: 14,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['ε=-dΦ/dt', 'ε=BLv', 'M=μ₀N₁N₂A/l'],
            topics: ['Faraday\'s Law', 'Lenz\'s Law', 'Inductance']
        },
        {
            id: 'phys-10',
            name: 'Alternating Current',
            priority: 'medium',
            marks: 12,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['V=V₀sinωt', 'Z=√(R²+X²)', 'tanφ=X/R'],
            topics: ['AC Circuits', 'Power Factor', 'Resonance', 'Transformers']
        },
        {
            id: 'phys-11',
            name: 'Ray Optics',
            priority: 'high',
            marks: 15,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['n₁sinθ₁=n₂sinθ₂', '1/f=1/v+1/u', 'P=1/f'],
            topics: ['Reflection', 'Refraction', 'Lenses', 'Mirrors']
        },
        {
            id: 'phys-12',
            name: 'Wave Optics',
            priority: 'medium',
            marks: 12,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['λ=a sinθ/n', 'Δ=λ/2', 'I=I₁+I₂+2√I₁I₂cosφ'],
            topics: ['Interference', 'Diffraction', 'Polarization']
        },
        {
            id: 'phys-13',
            name: 'Thermodynamics',
            priority: 'high',
            marks: 14,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['Q=ΔU+W', 'ΔU=nCᵥΔT', 'PV=nRT'],
            topics: ['Laws of Thermodynamics', 'Heat', 'Work']
        },
        {
            id: 'phys-14',
            name: 'Simple Harmonic Motion & Waves',
            priority: 'high',
            marks: 15,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['a=-ω²x', 'T=2π√(m/k)', 'v=fλ'],
            topics: ['Oscillations', 'Waves', 'Sound', 'Doppler Effect']
        },
        {
            id: 'phys-15',
            name: 'Modern Physics',
            priority: 'high',
            marks: 16,
            progress: 0,
            revisions: 0,
            confidence: 0,
            pyqCompletion: 0,
            status: 'neutral',
            ncertStatus: 'pending',
            formulas: ['E=hf', 'λ=h/p', 'N=N₀e^(-λt)'],
            topics: ['Photons', 'Atomic Structure', 'Nuclear Physics', 'Semiconductors']
        }
    ],

    // ============================================
    // HELPER METHODS
    // ============================================

    // Get all chapters
    getAllChapters() {
        return [...this.biology, ...this.chemistry, ...this.physics];
    },

    // Get chapters by subject
    getChaptersBySubject(subject) {
        return this[subject.toLowerCase()] || [];
    },

    // Get total marks for a subject
    getTotalMarksBySubject(subject) {
        const chapters = this.getChaptersBySubject(subject);
        return chapters.reduce((sum, ch) => sum + ch.marks, 0);
    },

    // Get all chapter marks
    getTotalMarks() {
        return this.biology.reduce((sum, ch) => sum + ch.marks, 0) +
            this.chemistry.reduce((sum, ch) => sum + ch.marks, 0) +
            this.physics.reduce((sum, ch) => sum + ch.marks, 0);
    },

    // Get high priority chapters
    getHighPriorityChapters() {
        return this.getAllChapters().filter(ch => ch.priority === 'high');
    },

    // Get chapters by priority
    getChaptersByPriority(priority) {
        return this.getAllChapters().filter(ch => ch.priority === priority);
    }
};
